server:
  port: 8081
spring:
  profiles:
    active: prod


# yml文件冒号和变量之间必须有空格
#person:
#  last-name: zhangsan
#  age: 18
#  sex: false
#  inst: {"k1":v1,"k2":v2}
#  loves:
#   - pingpang
#   - music
#   - movie
#  dog:
#   name: jojo
#   age: 19
